spring:
  application:
    name: unbox_trade
  
  config:
    import: "optional:file:.env[.properties]"

  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.postgresql.Driver}
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jwt:
    secret: ${SPRING_JWT_SECRET}

  cloud:
    openfeign:
      client:
        config:
          default:
            loggerLevel: basic
            connectTimeout: 1000
            readTimeout: 3000
          unbox-user:
            readTimeout: 5000
          product-service:
            readTimeout: 5000

logging:
  level:
    com.example.unbox_trade.common.client: DEBUG

# Custom Feign Client URLs
product-service:
  url: ${PRODUCT_SERVICE_URL:http://localhost:8082}

user-service:
  url: ${USER_SERVICE_URL:http://localhost:8081}

payment-service:
  url: ${TRADE_SERVICE_URL:http://localhost:8085}

order-service:
  url: ${ORDER_SERVICE_URL:http://localhost:8084}

cors:
  allowed-origins:
    - "${CORS_ALLOWED_ORIGINS:http://localhost:5173}"

springdoc:
  api-docs:
    path: /trade/v3/api-docs
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha
    custom-path: /css/swagger-custom.css
